# Generated by Django 5.0.1 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='создано'),
        ),
    ]
