# Generated by Django 5.0.1 on 2024-01-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
    ]
